spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres
    password: postgress
    driver-class-name: org.postgresql.Driver
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
        hibernate.format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace


